create table RETRIBUZIONE_MEDIA_2019 (
ISTITUZIONE  TEXT , 
CONTRATTO  TEXT , 
CATEGORIA  TEXT , 
STIPENDIO  TEXT , 
RIA  TEXT , 
TREDICESIMA  TEXT , 
STRAORDINARIO  TEXT , 
INDENNITA_FISSE  TEXT , 
ALTRE_ACCESSORIE  TEXT , 
TOT_RETR   TEXT )
