SELECT ISTITUZIONE, CATEGORIA, DESC_TIPO_ISTITUZIONE, DESC_ISTITUZIONE, (STIPENDIO+RIA+TREDICESIMA+STRAORDINARIO+INDENNITA_FISSE+ALTRE_ACCESSORIE) AS RETR_TOT
FROM conto_annuale.RETRIBUZIONE_MEDIA_2019
join ISTITUZIONI_CONTOANNUALE_2019_A on concat(CODI_TIPO_ISTITUZIONE,CODI_ISTITUZIONE)=ISTITUZIONE
where CONTRATTO='SSNA'
and CATEGORIA='MD'
order by RETR_TOT desc
